version: '3.8'
services:

  backend:
    container_name: backend
    image: docker.io/desoprotocol/backend:stable
    entrypoint: sh -c "sleep 6 && /deso/bin/backend run"
    volumes:
      - global_state:/db
    ports:
      - 17001:17001
      - 17000:17000
    depends_on:
      - database
    env_file:
      - ./.env
    environment:
      POSTGRES_URI: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable"
    expose:
      - "17001"
      - "17000"
    #restart: unless-stopped
  
  database:
    container_name: deso-db
    image: supabase/postgres:14.1.0
    user: postgres
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
    expose:
      - 5432
    command: postgres -c config_file=/etc/postgresql/postgresql.conf 

volumes:
  global_state:
  db: